name: Trigger On Push

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

  install-jq:
    runs-on: ubuntu-latest
    needs: checkout-repository
    steps:
      - name: Install jq
        run: sudo apt-get install jq

  get-api-token:
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SCOPE: "TM.Projects TM.Projects.Read TM.Projects.Write TM.TestCases TM.TestCases.Read TM.TestCases.Write TM.TestExecutions TM.TestExecutions.Read TM.TestExecutions.Write TM.TestSets TM.TestSets.Read TM.TestSets.Write"
      TOKEN_URL: "https://cloud.uipath.com/identity_/connect/token"
      API_URL: "https://cloud.uipath.com/interikeagroup/Test/testmanager_/api/v2"
    runs-on: ubuntu-latest
    needs: install-jq
    steps:
      - name: Get API token
        run: |
          response=$(curl --silent --write-out "\n%{http_code}" --request POST "$TOKEN_URL" --header "Content-Type: application/x-www-form-urlencoded" --data "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=client_credentials&scope=$SCOPE")
          echo $response
          response_body=$(echo "$response" | sed '$d')  # Remove last line (status code)
          status_code=$(echo "$response" | tail -n1)   # Get last line (status code)
          echo $response_body
          echo $status_code
          token=$(echo $status_code | jq -r '.access_token')          
          echo "ACCESS_TOKEN=$token" >> $GITHUB_ENV

  list-projects:
    env:
      API_URL: "https://cloud.uipath.com/interikeagroup/Test/testmanager_/api/v2"
    runs-on: ubuntu-latest
    needs: get-api-token
    steps:
      - name: List projects
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET "$API_URL/Projects" -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" -H "Accept: application/json")
          echo "Response: $response"
